### PR TITLE
Modifications in the structure of the libraries that compose the toolbox

### PR DESCRIPTION
**Pull request by Cristina-Tobias**
Changes proposed in this pull request:

- Functions have been renamed
- RSS has been moved from the visualization library to the processing library
- Some input arguments have been changed to avoid confusion

This pull request closes de issue Reestructure the toolbox #3

### CODE REVIEW

**Comment by eurunuela** [comment]
Hey @Cristina-Tobias ! 

This is great. One comment before I review though, could you run [black](https://github.com/psf/black) and [isort](https://pycqa.github.io/isort/) on the package and commit the changes? This would make reading the code much easier.

**Comment by Cristina-Tobias** [comment]
<-- The changes made to the toolbox are the following:
- The names of the variables that could cause confusion have been changed
- All of the functions of processing have been put together
- Some functions have had their input arguments changed so as to avoid confusion
<-- This commit closes the issue #3 -->

**Comment by eurunuela** [comment]
> <-- The changes made to the toolbox are the following:
> 
> * The names of the variables that could cause confusion have been changed
> * All of the functions of processing have been put together
> * Some functions have had their input arguments changed so as to avoid confusion
>   <-- This commit closes the issue [Reestructure the toolbox #3](https://github.com/Cristina-Tobias/clustintime/issues/3) -->

You should write this on the description of the pull request (PR). It's the very first text box on the top of the PR.

**Review by eurunuela — APPROVED** [review]
I think it's good that we merge this. We will look at the specifics once it's merged.

**Pull request merged**
